/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f103xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void clock_init(void);
void gpio_init(void);
void delay(void);

int main(void)
{
	clock_init();
	gpio_init();

	while(1) {
		GPIOA->ODR ^= (1 << 5);
		delay();
	}

	return 0;
}

void clock_init(void) {
	RCC->CR |= (1 << 0);
//	while (RCC->CR ^ (1 << 1));
	RCC->APB2ENR |= (1 << 2) | (1 << 4);
}

void gpio_init(void) {
	GPIOA->CRL &= 0;
	// PA12 as output push pull
	GPIOA->CRL |= (1 << 20);

//	GPIOC->CRH |= (00 << )
}

void delay(void) {
	int32_t count = 1000000;
	while (count--);
}
