/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f103xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void gpio_init(void);
void clock_init(void);
void exti_init(void);
void delay(void);

int main(void)
{
	clock_init();
	gpio_init();
	exti_init();

	while (1)
	{
		delay();
	}

}

void EXTI15_10_IRQHandler(void) {
	//Clear pending flag
	EXTI->PR |= (1 << 13);
	//Toggle led
	GPIOA->ODR ^= (1 << 5);
}

void gpio_init(void)
{
	// configure led
	GPIOA->CRL &= 0;
	// PA5 as output push pull
	GPIOA->CRL |= (1 << 20);
	// configure button
	GPIOC->CRH &= 0;
	// PC13 as input, floating because board supports external pullup
	GPIOC->CRH |= (1 << 22);
	// GPIOC->ODR |= (1 << 13);
}

void exti_init(void)
{
	// enable exti line 13, PC13
	AFIO->EXTICR[3] |= (1 << 5);
	// interrupt trigger on rising edge
	EXTI->IMR |= 1 << 13;
	EXTI->FTSR |= (1 << 13);
	//enable IRQ 40
	NVIC->ISER[1] |= 1 << 8;
}

void clock_init(void)
{
	// using HSI clock
	RCC->CR |= (1 << 0);
	/*PORT A*/
	RCC->APB2ENR |= (1<<2);

	/*PORT C*/
	RCC->APB2ENR |= (1<<4);

	/*AFIO*/
	RCC->APB2ENR |= (1<<0);
}

void delay(void) {
	int32_t count = 100000;
	while (count--);
}
